import React, { useState, useEffect } from 'react';
import { 
  FileText, Plus, Search, Filter, Eye, CheckCircle, XCircle, Clock, 
  AlertTriangle, Loader2, RefreshCw, ChevronDown, ChevronUp, Check, X 
} from 'lucide-react';
import { api } from '../../services/api';
import { inventoryService } from '../../services/inventoryService';
import { useAuth } from '../../context/AuthContext';
import { useNavigate } from 'react-router-dom';
import { toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const PurchaseRequisitions = () => {
  // State management
  const { user } = useAuth();
  const navigate = useNavigate();
  const isInventoryManager = user?.role === 'Inventory Manager';

  const [inventoryItems, setInventoryItems] = useState([]);
  const [requisitions, setRequisitions] = useState([]);
  const [showAutoGenerated, setShowAutoGenerated] = useState(true);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [searchTerm, setSearchTerm] = useState('');
  const [selectedStatus, setSelectedStatus] = useState('all');
  const [isGenerating, setIsGenerating] = useState(false);
  const [expandedRequisitions, setExpandedRequisitions] = useState(new Set());

  // Fetch data from API
  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true);
        console.log('🔄 Fetching inventory items and requisitions...');
        
        // Fetch data with detailed error handling
        const [inventoryRes, requisitionsRes] = await Promise.all([
          await api.get('/inventory/').catch(err => {
            console.error('Error fetching inventory items:', {
              message: err.message,
              response: err.response?.data,
              status: err.response?.status,
              config: {
                url: err.config?.url,
                method: err.config?.method,
                headers: err.config?.headers
              }
            });
            // Filter out inactive items from frontend as well
            if (err.response?.data) {
              console.log('🔍 Filtering inactive items from response:', err.response.data.filter(item => item.is_active !== false).length, 'items filtered');
              err.response.data = err.response.data.filter(item => item.is_active !== false);
            }
            throw err; // Re-throw to be caught by outer catch
          }),
          api.get('/purchase-requisitions').catch(err => {
            console.error('Error fetching purchase requisitions:', {
              message: err.message,
              response: err.response?.data,
              status: err.response?.status
            });
            throw err; // Re-throw to be caught by outer catch
          })
        ]);
        
        console.log('📦 Inventory items fetched:', inventoryRes.data);
        console.log('📊 Inventory items type:', typeof inventoryRes.data);
        console.log('📏 Inventory items length:', inventoryRes.data?.length);
        console.log('📋 Requisitions fetched:', requisitionsRes.data);
        console.log('📋 Requisitions type:', typeof requisitionsRes.data);
        console.log('📏 Requisitions length:', requisitionsRes.data?.length);
        
        // Double-check filtering
        const activeItems = inventoryRes.data?.filter(item => item.is_active !== false) || [];
        console.log('✅ Active items after filtering:', activeItems.length);
        
        setInventoryItems(activeItems);
        setRequisitions(requisitionsRes.data);
      } catch (error) {
        console.error('Error in fetchData:', {
          message: error.message,
          response: error.response?.data,
          status: error.response?.status,
          stack: error.stack
        });
        
        // Show more detailed error message to user
        const errorMessage = error.response?.data?.message || 
                           error.message || 
                           'Failed to load data. Please check the console for details.';
        
        toast.error(errorMessage);
      } finally {
        setLoading(false);
        setRefreshing(false);
      }
    };

    fetchData();
  }, []);

  // Check for items that need reordering based on Min-Max rule
  const needsReordering = inventoryItems.filter(item => 
    item.is_active !== false && item.current_stock <= item.reorder_point
  );

  // Generate purchase requisitions for items below min level
  const handleGenerateRequisitions = async () => {
    try {
      setIsGenerating(true);
      // First, check if there are items that need reordering
      const itemsNeedingReorder = inventoryItems.filter(
        item => item.current_stock <= item.reorder_point
      );

      if (itemsNeedingReorder.length === 0) {
        toast.info('No items need reordering at this time');
        return;
      }

      const response = await api.post('/purchase-requisitions/generate-from-stock');
      
      if (response.data && response.data.message) {
        toast.success(response.data.message);
      } else {
        toast.success('Purchase requisitions generated successfully');
      }
      
      // Refresh data
      const [inventoryRes, requisitionsRes] = await Promise.all([
        api.get('/inventory/'),
        api.get('/purchase-requisitions')
      ]);
      const activeItems = inventoryRes.data?.filter(item => item.is_active !== false) || [];
      setInventoryItems(activeItems);
      setRequisitions(requisitionsRes.data);
    } catch (error) {
      console.error('Error generating requisitions:', error);
      
      // Show more detailed error message
      const errorMessage = error.response?.data?.message || 
                         error.message || 
                         'Failed to generate requisitions. Please try again.';
      
      toast.error(errorMessage);
      
      // Log full error for debugging
      if (error.response) {
        console.error('Error response data:', error.response.data);
        console.error('Error status:', error.response.status);
        console.error('Error headers:', error.response.headers);
      } else if (error.request) {
        console.error('No response received:', error.request);
      } else {
        console.error('Error setting up request:', error.message);
      }
    } finally {
      setIsGenerating(false);
    }
  };

  // Handle refresh
  const handleRefresh = async () => {
    setRefreshing(true);
    const [inventoryRes, requisitionsRes] = await Promise.all([
      api.get('/inventory/'),
      api.get('/purchase-requisitions')
    ]);
    const activeItems = inventoryRes.data?.filter(item => item.is_active !== false) || [];
    setInventoryItems(activeItems);
    setRequisitions(requisitionsRes.data);
    setRefreshing(false);
  };

  // Filter requisitions based on search and status
  const filteredRequisitions = requisitions.filter(req => {
    const matchesSearch = (req.pr_number || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
                         (req.items?.some(item => 
                           (item.sku || '').toLowerCase().includes(searchTerm.toLowerCase()) ||
                           (item.name || '').toLowerCase().includes(searchTerm.toLowerCase())
                         ) || false);
    const matchesStatus = selectedStatus === 'all' || req.status === selectedStatus.toUpperCase();
    const matchesAutoGenerated = showAutoGenerated ? true : !req.auto_generated;
    
    return matchesSearch && matchesStatus && matchesAutoGenerated;
  });

  // Calculate suggested min/max levels
  const calculateSuggestedLevels = (item) => {
    const suggestedMin = Math.ceil((item.average_daily_usage * item.lead_time_days) + item.safety_stock);
    const suggestedMax = suggestedMin + Math.ceil(item.average_daily_usage * 30); // 30-day reorder cycle
    return { suggestedMin, suggestedMax };
  };

  // Update item levels
  const updateItemLevels = async (itemId, newMin, newMax) => {
    try {
      await api.put(`/inventory/${itemId}`, {
        reorder_point: newMin,
        safety_stock: newMax
      });
      
      setInventoryItems(prev => 
        prev.map(item => 
          item.id === itemId 
            ? { 
                ...item, 
                reorder_point: newMin, 
                safety_stock: newMax 
              }
            : item
        )
      );
      toast.success('Item levels updated successfully');
    } catch (error) {
      console.error('Error updating item levels:', error);
      toast.error('Failed to update item levels');
    }
  };

  // Toggle requisition details
  const toggleRequisitionDetails = (reqId) => {
    const newExpanded = new Set(expandedRequisitions);
    if (newExpanded.has(reqId)) {
      newExpanded.delete(reqId);
    } else {
      newExpanded.add(reqId);
    }
    setExpandedRequisitions(newExpanded);
  };

  // Approve a requisition
  const approveRequisition = async (reqId) => {
    if (!isInventoryManager) {
      toast.error('Only Inventory Managers can approve requisitions');
      return;
    }

    try {
      await api.put(`/purchase-requisitions/${reqId}/approve`);
      setRequisitions(prev => 
        prev.map(req => 
          req.id === reqId 
            ? { 
                ...req, 
                status: 'INWARD_APPROVED', 
                approved_date: new Date().toISOString() 
              } 
            : req
        )
      );
      toast.success('Requisition inward-approved successfully');
    } catch (error) {
      console.error('Error approving requisition:', error);
      toast.error('Failed to approve requisition');
    }
  };

  // Reject a requisition
  const rejectRequisition = async (reqId) => {
    const reason = prompt('Please enter the reason for rejection:');
    if (!reason) return;

    if (!isInventoryManager) {
      toast.error('Only Inventory Managers can reject requisitions');
      return;
    }
    
    try {
      await api.put(`/purchase-requisitions/${reqId}/reject`, { reason });
      setRequisitions(prev => 
        prev.map(req => 
          req.id === reqId 
            ? { 
              ...req, 
                status: 'REJECTED', 
                rejected_date: new Date().toISOString(),
                rejection_reason: reason
              } 
            : req
        )
      );
      toast.success('Requisition rejected');
    } catch (error) {
      console.error('Error rejecting requisition:', error);
      toast.error('Failed to reject requisition');
    }
  };

  // Delete a requisition
  const deleteRequisition = async (reqId) => {
    if (!window.confirm('Are you sure you want to delete this requisition?')) return;
    
    try {
      console.log('📤 Sending DELETE request to:', `/purchase-requisitions/${reqId}`);
      const response = await api.delete(`/purchase-requisitions/${reqId}`);
      console.log('📋 DELETE Response status:', response.status);
      console.log('📋 DELETE Response data:', response.data);
      
      setRequisitions(prev => prev.filter(req => req.id !== reqId));
      toast.success('Requisition deleted successfully');
      
      // Also refresh inventory items in case an item was deleted
      console.log('🔄 Refreshing inventory after delete...');
      const inventoryRes = await api.get('/inventory/');
      console.log('📦 Inventory after delete:', inventoryRes.data);
      const activeItems = inventoryRes.data?.filter(item => item.is_active !== false) || [];
      setInventoryItems(activeItems);
    } catch (error) {
      console.error('❌ Error deleting requisition:', error);
      toast.error('Failed to delete requisition');
    }
  };

  // Delete an inventory item
  const handleDeleteInventoryItem = async (itemId) => {
    try {
      await api.delete(`/inventory/${itemId}`);
      setInventoryItems(prev => prev.filter(item => item.id !== itemId));
      toast.success('Inventory item deleted successfully');
    } catch (error) {
      console.error('Error deleting inventory item:', error);
      toast.error('Failed to delete inventory item');
    }
  };

  const getStatusLabel = (status) => {
    switch (status) {
      case 'PENDING':
        return 'Pending';
      case 'INWARD_APPROVED':
        return 'Inward Approved';
      case 'REJECTED':
        return 'Rejected';
      default:
        return status || 'Unknown';
    }
  };

  const getStatusClasses = (status, isAutoGenerated) => {
    if (status === 'INWARD_APPROVED') {
      return 'bg-blue-100 text-blue-800';
    }

    if (status === 'REJECTED') {
      return 'bg-red-100 text-red-800';
    }

    if (isAutoGenerated) {
      return 'bg-blue-100 text-blue-800';
    }

    return 'bg-yellow-100 text-yellow-800';
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="flex flex-col items-center">
          <Loader2 className="w-8 h-8 text-blue-500 animate-spin mb-2" />
          <p>Loading inventory data...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="container mx-auto px-4 py-8">
      {/* Inventory Summary */}
      <div className="mb-8">
        <div className="flex justify-between items-center mb-6">
          <h1 className="text-2xl font-bold text-gray-800">Inventory Management</h1>
          <div className="flex space-x-3">
            <button
              onClick={() => navigate('/purchasing/orders')}
              className="flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
            >
              View Purchase Orders
            </button>
            <button
              onClick={handleRefresh}
              disabled={refreshing}
              className="flex items-center px-4 py-2 border border-gray-300 rounded-md shadow-sm text-sm font-medium text-gray-700 bg-white hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
            >
              <RefreshCw className={`w-4 h-4 mr-2 ${refreshing ? 'animate-spin' : ''}`} />
              {refreshing ? 'Refreshing...' : 'Refresh'}
            </button>
            <button
              onClick={handleGenerateRequisitions}
              disabled={isGenerating}
              className="flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
            >
              <Plus className="w-4 h-4 mr-2" />
              {isGenerating ? 'Generating...' : 'Generate Requisitions'}
            </button>
          </div>
        </div>

        {/* Inventory Summary Cards */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
          <div className="bg-white p-4 rounded-lg shadow">
            <div className="flex items-center">
              <div className="p-3 rounded-full bg-blue-100 text-blue-600">
                <FileText className="w-6 h-6" />
              </div>
              <div className="ml-4">
                <p className="text-sm font-medium text-gray-500">Total Items</p>
                <p className="text-2xl font-semibold text-gray-900">{inventoryItems.length}</p>
              </div>
            </div>
          </div>
          <div className="bg-white p-4 rounded-lg shadow">
            <div className="flex items-center">
              <div className="p-3 rounded-full bg-yellow-100 text-yellow-600">
                <AlertTriangle className="w-6 h-6" />
              </div>
              <div className="ml-4">
                <p className="text-sm font-medium text-gray-500">Needs Reorder</p>
                <p className="text-2xl font-semibold text-gray-900">
                  {needsReordering.length}
                </p>
              </div>
            </div>
          </div>
          <div className="bg-white p-4 rounded-lg shadow">
            <div className="flex items-center">
              <div className="p-3 rounded-full bg-green-100 text-green-600">
                <CheckCircle className="w-6 h-6" />
              </div>
              <div className="ml-4">
                <p className="text-sm font-medium text-gray-500">Active Requisitions</p>
                <p className="text-2xl font-semibold text-gray-900">
                  {requisitions.filter(r => r.status === 'PENDING' || r.status === 'INWARD_APPROVED').length}
                </p>
              </div>
            </div>
          </div>
          <div className="bg-white p-4 rounded-lg shadow">
            <div className="flex items-center">
              <div className="p-3 rounded-full bg-purple-100 text-purple-600">
                <Clock className="w-6 h-6" />
              </div>
              <div className="ml-4">
                <p className="text-sm font-medium text-gray-500">This Month</p>
                <p className="text-2xl font-semibold text-gray-900">
                  {requisitions.filter(r => new Date(r.created_at).getMonth() === new Date().getMonth()).length}
                </p>
              </div>
            </div>
          </div>
        </div>

        {/* Inventory Table */}
        <div className="bg-white shadow overflow-hidden sm:rounded-lg mb-8">
          <div className="px-4 py-5 sm:px-6 border-b border-gray-200">
            <h3 className="text-lg leading-6 font-medium text-gray-900">Inventory Items</h3>
            <p className="mt-1 max-w-2xl text-sm text-gray-500">
              Current inventory levels and reorder status
            </p>
          </div>
          <div className="overflow-x-auto">
            <table className="min-w-full divide-y divide-gray-200">
              <thead className="bg-gray-50">
                <tr>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Item</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Current Stock</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Min Level</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Safety Stock</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                  <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
                </tr>
              </thead>
              <tbody className="bg-white divide-y divide-gray-200">
                {inventoryItems.map((item) => {
                  const currentStock = item.current_stock ?? 0;
                  const needsReorder = currentStock <= item.reorder_point;
                  return (
                    <tr key={item.id} className={needsReorder ? 'bg-red-50' : ''}>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="font-medium text-gray-900">{item.name}</div>
                        <div className="text-sm text-gray-500">{item.sku}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${
                          needsReorder ? 'bg-red-100 text-red-800' : 'bg-green-100 text-green-800'
                        }`}>
                          {currentStock} {item.unit_of_measure}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {item.reorder_point}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {item.safety_stock}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        {needsReorder ? (
                          <span className="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-yellow-100 text-yellow-800">
                            Needs Reorder
                          </span>
                        ) : (
                          <span className="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                            In Stock
                          </span>
                        )}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                        <button
                          onClick={() => {
                            const newReorderPoint = prompt('Enter new reorder point:', item.reorder_point);
                            if (newReorderPoint && !isNaN(newReorderPoint)) {
                              const newSafetyStock = prompt('Enter new safety stock:', item.safety_stock);
                              if (newSafetyStock && !isNaN(newSafetyStock)) {
                                updateItemLevels(item.id, parseInt(newReorderPoint), parseInt(newSafetyStock));
                              }
                            }
                          }}
                          className="text-blue-600 hover:text-blue-900"
                        >
                          Edit Levels
                        </button>
                        <button
                          onClick={() => {
                            if (window.confirm(`Are you sure you want to delete "${item.name}"?`)) {
                              handleDeleteInventoryItem(item.id);
                            }
                          }}
                          className="text-red-600 hover:text-red-900 ml-2"
                        >
                          Delete Item
                        </button>
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* Purchase Requisitions */}
      <div className="bg-white rounded-lg shadow overflow-hidden">
        <div className="p-4 border-b flex justify-between items-center">
          <div>
            <h2 className="text-lg font-semibold">Purchase Requisitions</h2>
            <p className="text-sm text-gray-500">
              {requisitions.filter(r => ['PENDING', 'INWARD_APPROVED'].includes(r.status)).length} pending, {requisitions.length} total
            </p>
          </div>
          <div className="flex items-center space-x-4">
            <div className="flex items-center">
              <input
                type="checkbox"
                id="showAutoGenerated"
                checked={showAutoGenerated}
                onChange={(e) => setShowAutoGenerated(e.target.checked)}
                className="mr-2 h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
              />
              <label htmlFor="showAutoGenerated" className="text-sm text-gray-700">
                Show Auto-generated
              </label>
            </div>
            <select
              value={selectedStatus}
              onChange={(e) => setSelectedStatus(e.target.value)}
              className="border rounded-md px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            >
              <option value="all">All Status</option>
              <option value="pending">Pending</option>
              <option value="inward_approved">Inward Approved</option>
              <option value="rejected">Rejected</option>
            </select>
          </div>
        </div>
        
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Item</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Current Stock</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Quantity</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Status</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Date</th>
                <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {filteredRequisitions.length > 0 ? (
                filteredRequisitions.map((req) => (
                  <tr key={req.id} className={req.auto_generated ? 'bg-blue-50' : ''}>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="font-medium text-gray-900">
                        {req.items?.[0]?.name || 'Multiple Items'}
                      </div>
                      <div className="text-sm text-gray-500">
                        {req.pr_number}
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {req.items?.[0]?.current_stock || 'N/A'} {req.items?.[0]?.unit_of_measure || ''}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                        {req.items?.reduce((sum, item) => sum + item.quantity, 0)} items
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${getStatusClasses(req.status, req.auto_generated)}`}>
                        {getStatusLabel(req.status)}
                        {req.auto_generated ? ' (Auto)' : ''}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                      {new Date(req.created_at).toLocaleDateString()}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-sm font-medium">
                      <div className="flex items-center gap-2">
                        <button
                          onClick={() => navigate('/purchasing/orders')}
                          className="text-blue-600 hover:text-blue-900 px-2 py-1.5 text-sm font-medium"
                        >
                          View POs
                        </button>
                        {req.status === 'PENDING' && isInventoryManager && (
                          <>
                            <button 
                              onClick={() => approveRequisition(req.id)}
                              className="flex items-center px-3 py-1.5 bg-green-600 text-white rounded-md hover:bg-green-700 transition-colors text-sm font-medium"
                            >
                              <Check className="w-4 h-4 mr-1.5" />
                              Approve
                            </button>
                            <button 
                              onClick={() => rejectRequisition(req.id)}
                              className="flex items-center px-3 py-1.5 bg-red-600 text-white rounded-md hover:bg-red-700 transition-colors text-sm font-medium"
                            >
                              <X className="w-4 h-4 mr-1.5" />
                              Reject
                            </button>
                            <button 
                              onClick={() => deleteRequisition(req.id)}
                              className="text-gray-600 hover:text-red-600 px-2 py-1.5 text-sm font-medium"
                            >
                              Delete
                            </button>
                          </>
                        )}
                      </div>
                    </td>
                  </tr>
                ))
              ) : (
                <tr>
                  <td colSpan="6" className="px-6 py-4 text-center text-sm text-gray-500">
                    No purchase requisitions found
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Min-Max Rule Explanation */}
      <div className="mt-8 bg-blue-50 border-l-4 border-blue-400 p-4 rounded">
        <div className="flex">
          <div className="flex-shrink-0">
            <svg className="h-5 w-5 text-blue-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor">
              <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
            </svg>
          </div>
          <div className="ml-3">
            <h3 className="text-sm font-medium text-blue-800">About Min-Max Inventory Management</h3>
            <div className="mt-2 text-sm text-blue-700">
              <p className="mb-2">
                The <strong>Min-Max Rule</strong> helps maintain optimal inventory levels by defining two key points:
              </p>
              <ul className="list-disc pl-5 space-y-1">
                <li><strong>Minimum Level (Min):</strong> When stock reaches this level, a purchase requisition is automatically generated.</li>
                <li><strong>Maximum Level (Max):</strong> The target stock level after replenishment.</li>
              </ul>
              <p className="mt-2">
                <strong>Formula:</strong> Reorder Quantity = Maximum Level - Current Stock
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PurchaseRequisitions;